title:            try { } catch { } me
description:      A coding blog... mostly

# put your disqus here
disqus_shortname: trycatchme
reading_time:     true 
words_per_minute: 200
logo:             images/logo.png 
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: https://eoincampbell.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about/'
  - title: 'Categories'
    url: '/categories/'
    type: categories
  - title: 'Dev'
    url: '#'
  - title: 'Links'
    url: '#'
    submenu:
      - title: 'Flickr'
        url: 'http://www.flickr.com/photos/eoincampbell/sets/'

# Owner/author information
owner:
  name:           Eoin Campbell
  site:           http://trycatch.me
  avatar:         images/avatar.jpg
  bio:            "TODO - 2 Liner"
  email:          eoin.campbell+blog@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: eoinc
  # GitHub nick for use in follow button in author block.
  github: eoincampbell

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter: eoinc

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/eoincampbell"
  - title: "linkedin"
    url: "https://linkedin.com/in/eoincampbell"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/30155/eoin-campbell"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Dublin
locale:      en_IE
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
plugins: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
